modLoader="javafml"
loaderVersion="[43,)"
license="LGPL 2.1"
issueTrackerURL="https://github.com/EtiTheSpirit/TheOriMod/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="The Ori Mod"
displayURL="https://etithespir.it/minecraft"
updateJSONURL="https://etithespir.it/minecraft/version.json"
logoFile="orimod.png"
credits="Check the description!"
authors="§bEti the Spirit§r AKA §cXan the Dragon§r"
description='''
${mod_desc}

§lCredits:§r
- §bEtiTheSpirit§r - yall know that meme of obama giving himself a medal?
- §bOri Community§r - Your interest in my work fuels my desire to make it better.
- §bMoon Studios§r - Open ended lore is what makes stuff like this feel cohesive.
§o* Without you, this mod could not work the way it does today! *§r

§lForge Discord Mention Honorarium:§r
These folks in the Forge discord helped me out so much with the development of the mod that it's only fair to list their names here.
- §cMcJty§r - You have the patience of a saint. Genuinely speechless.
- §cRobotGryphon§r - Made Compact Machines, where I sourced instrumental debug render code from.
- §bSizableShrimp§r - Made some helpful stuff for Gradle that enables better tooling for the mod.
- §bgigaherz§r - Made GraphLib, which, while unused, was very helpful in figuring out Light tech.
- §bmisode§r - The Worldgen Wizard, instrumental in getting Gorlek Crystals to work.
- §6Random§r
- §6diesieben07§r
- §6Commable§r
- §6Lupicus§r
- §6XFactHD§r
§o* Thank you all for your help! *§r
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[43,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
# Update from Eti: "Next major version" is now 1.19.3 insterad of 1.20. Thanks Minecraft.
    versionRange="[1.19.2,1.19.3)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=false
    versionRange="[8.6.0,)"
    ordering="BEFORE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="configured"
    mandatory=false
    versionRange="[2.0.1,)"
    ordering="BEFORE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.6.3,)"
    ordering="BEFORE"
    side="CLIENT"
[modproperties.${mod_id}]
    configuredBackground="orimod:textures/configured/tintgrass.png"