modLoader="javafml"
loaderVersion="[43,)"
license="GNU General Public License"
issueTrackerURL="https://github.com/EtiTheSpirit/TheOriMod/issues/new/choose"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="The Ori Mod"
displayURL="https://etithespir.it/minecraft"
logoFile="orimod.png"
credits=''':
§lThe Main Creds:§r
- §bEtiTheSpirit§r - look at me ma
- §bOri Community§r - Your interest fuels my desire to create.
- §bMoon Studios§r - Open ended lore is what makes stuff like this feel cohesive.
§o* Without you, this mod could not work the way it does today! *§r

§lForge Discord Mention Honorarium:§r
These folks in the Forge discord helped me out substantially in the development of the mod.
- §cRobotGryphon§r - Made Compact Machines, where I sourced instrumental debug render code from.
- §cMcJty§r - Has the patience of a saint. You make the modding process easier for everyone!
- §bSizableShrimp§r - Makes helpful stuff for Gradle that enables better tooling for the mod.
- §6Random§r
- §6diesieben07§r
- §6Commable§r
- §6gigaherz§r
- §6Lupicus§r
- §6XFactHD§r
§o* Thank you all for your help with my endeavor of making this mod! *§r
'''
authors="§bEti the Spirit§r AKA §cXan the Dragon§r"
description='''
Play as a Spirit! This mod aims to append mechanics and objects from the §oOri§r game franchise. It also implements some fanon concepts I wrote.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.${mod_id}]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[41,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="jade"
    mandatory=false
    versionRange="[8.1.1,)"
    ordering="BEFORE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="configured"
    mandatory=false
    versionRange="[1.5.8,)"
    ordering="BEFORE"
    side="CLIENT"
[[dependencies.${mod_id}]]
    modId="catalogue"
    mandatory=false
    versionRange="[1.6.3,)"
    ordering="BEFORE"
    side="CLIENT"
[modproperties.orimod]
    configuredBackground="orimod:textures/configured/tintgrass.png"